execute:
  freeze: auto
  cache: false

resource-path:
  - tex/elsevier/els-cas-templates

format:
  pdf:
    documentclass: cas-sc
    classoption:
      - review
    bibliography: references.bib
    biblio-style: cas-model2-names
    number-sections: true
    keep-tex: true
    header-includes: |
      \let\NewNegationCommand\relax
      \usepackage{amssymb}
